### ISSUE TITLE
Improve build system

### ISSUE THREAD

**Issue by ramtej** [schedulix/schedulix#9]
Hi guys, 
I;m just about to try out schedulix for my startup. I like the core concept
as it is clean, solid and simple. 

However, the "make" based build system is pretty outdated. There are any plans to support maven or 
even gradle (much better) ?

Thank you. 

Cheers, 
jj

**Comment by schedulix** [comment]
Hi JJ,

first of all thank you for your praise.

I agree, "make" isn't the most modern tool ever, but on the other side it is still widely used.
If I think about installing open source software, the common procedure that comes to mind is

./configure
make
make test
make install

And of course there's other software that has to be built with ant, maven, gradle or whatever.
Normally such software requires extra steps because the build tools have to be compiled and installed first.

Now "outdated" isn't a real argument to replace something. If I think about a hammer, I think of a tool that exists since thousands of years. That must be pretty outdated. However, it is still used because it is an optimal solution  for some problems.

Our solution to build schedulix using make works and is easy to use. For me makefiles are easy to maintain, because I know how to use make and how to write makefiles.

Hence we have a working and maintainable solution, using tools that are available everywhere.
That isn't a strong motivation to change it, to be honest.

On the other hand, schedulix is open source software. Nothing can stop you from building an alternative build system. And if you can explain me the benefits of your new solution over our make system, I will definitely consider adapting it.

Side note:
If you run into problems or have questions in any form, there is a schedulix google group which we actively maintain. Your question here is at a correct place, since it definitely focusses on the source code, not on the usage. But if you, for instance, want to know how to implement mutual exclusion of jobs, the google group would be the perfect place to ask.

Best regards,

Ronald

**Comment by ramtej** [comment]
Hi Roland, 

thank you for your answer. Pls find my comments below : 

"
_If I think about installing open source software, the common procedure that comes to mind is
./configure
 make
 make test
 make install_
"
From my perspective - No. Since Schedulix is mainly a Java Project, there are definitely other build systems available - and - from my perspective required. 

I see the point that outdated is not an argument, but the reason why I mentioned e.g. gradle is the fact that one has to manage (transitive) depenencies.

For now there are just a few of such dependencies required for Schedulix, but the reason I asked is that I need e.g. a integration with Fluentd , Telegram, Jira and  I;m willing to contribute but not sure if I would do it based on the "make" build approach.

Pls take the above lines as my personal opinion. Schedulix is a valuable contribution to the open source community, so I want to say thank you !

Cheers, 
jj

**Comment by schedulix** [comment]
Hi JJ,

don't worry, everybody is entitled to have his/hers own opinion. In fact this is the key to improvement.
If we develop a new feature we spend a lot of time discussing about it. Each of us defending his own opinion but at the same time respecting the other's opinion and trying to understand why this opinion differs so much from one's own.
Many times it turned out that none of us really understood the problem but more only a part of it.
The discussion led to a better understanding of the real and often underlying problem we tried to solve.

Because of the success of this approach (I could quote you as a proof), I don't give in easily. I need to be convinced.
As I said already, I am not against any other build method. But at least it should show benefits over the current build system which works and is easy to maintain.
There's actually only one situation (of which I know) which isn't handled very well: If, for whatever reason, a build has been interrupted a subsequent "make" takes ages and it's a better idea to do a "make new".
As you see, a little help from my side for your case :-)

An integration with other software products sounds good. The main work will be to specify and implement the integration. The simple part will be to integrate the extension into whatever build system.
We might also work together on these issues. That would perhaps lead to the use of another build system (I get an insight), or eliminate/reduce your aversion against "make".

Regards,

Ronald

**Comment by ramtej** [comment]
Hi Roland, 

thanks. Ok, I will screw together a gradle build, when I will have some free cycles. The only difficulty I see are the natives that has to be build as well, but I will try to find a elegant solution for it. 

Cheers, 
jj
